// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwQ0oKyfxQPSNDNdn4WUy_vcWp2YFO5s',
    appId: '1:896219547833:web:12b9d5c8fe4471cb33f368',
    messagingSenderId: '896219547833',
    projectId: 'entrega-136f8',
    authDomain: 'entrega-136f8.firebaseapp.com',
    databaseURL: 'https://entrega-136f8-default-rtdb.firebaseio.com',
    storageBucket: 'entrega-136f8.firebasestorage.app',
    measurementId: 'G-W2J0J086BT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaHUWGm49107zG0zNT3yQIvMbqeX_jKg',
    appId: '1:896219547833:ios:174442f437545e5f33f368',
    messagingSenderId: '896219547833',
    projectId: 'entrega-136f8',
    databaseURL: 'https://entrega-136f8-default-rtdb.firebaseio.com',
    storageBucket: 'entrega-136f8.firebasestorage.app',
    iosClientId: '896219547833-5ekpm941bndjtp0udnh7mt4uis19vnus.apps.googleusercontent.com',
    iosBundleId: 'com.example.userWeb',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaHUWGm49107zG0zNT3yQIvMbqeX_jKg',
    appId: '1:896219547833:ios:174442f437545e5f33f368',
    messagingSenderId: '896219547833',
    projectId: 'entrega-136f8',
    databaseURL: 'https://entrega-136f8-default-rtdb.firebaseio.com',
    storageBucket: 'entrega-136f8.firebasestorage.app',
    iosClientId: '896219547833-5ekpm941bndjtp0udnh7mt4uis19vnus.apps.googleusercontent.com',
    iosBundleId: 'com.example.userWeb',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIj6ojaA7WgEf9VFQeQNPwHp6gYiLh6Xo',
    appId: '1:896219547833:android:bd9100c8dd30931033f368',
    messagingSenderId: '896219547833',
    projectId: 'entrega-136f8',
    databaseURL: 'https://entrega-136f8-default-rtdb.firebaseio.com',
    storageBucket: 'entrega-136f8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjwQ0oKyfxQPSNDNdn4WUy_vcWp2YFO5s',
    appId: '1:896219547833:web:5e4936a3fe1a2ce133f368',
    messagingSenderId: '896219547833',
    projectId: 'entrega-136f8',
    authDomain: 'entrega-136f8.firebaseapp.com',
    databaseURL: 'https://entrega-136f8-default-rtdb.firebaseio.com',
    storageBucket: 'entrega-136f8.firebasestorage.app',
    measurementId: 'G-YY4XQ8GMP8',
  );

}